serenity.project.name=Serenity Cucumber Automation
# CucumberWithSerenity writes JSON + HTML here automatically when you run RunTests from IDE
serenity.outputDirectory=output/serenity-reports-st
serenity.report.encoding=UTF-8
serenity.parallel.enabled=true
serenity.parallel.maxthreads=4
